### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by mebrahimkhas** [tomduese/ds-fraud-detection#1]
Milestone 1: First Model aka Baseline - Day 2 (12:00)
 
What is "aka Baseline"? 
a baseline is a reference point for measuring progress against a plan. It is the original plan that is used as a basis for comparison with actual progress. "Aka Baseline" could refer to an alternative or additional baseline that is used for this purpose.

**Comment by tomduese** [comment]
@mebrahimkhas : for milestones there is a specific option that github has implemented, see the milestone thing in the top bar when you are at the issues page. an issue is for doing things, like creating the baseline model

**Comment by tomduese** [comment]
this is why i would close this one. I have already created all the milestones and we can add issues to them.
